### ISSUE TITLE
ImGui Profiler?

### ISSUE THREAD

**Issue by skl131313** [arnaud-jamin/Spell#1]
This is off topic, but the other thread is closed and github doesn't have discussions/messaging.

I was just wondering how you implemented this profiler?
https://github.com/ocornut/imgui/issues/973#issuecomment-312788074

**Comment by arnaud-jamin** [comment]
You can check it here:
https://github.com/arnaud-jamin/imgui/blob/master/profiler.cpp
https://github.com/arnaud-jamin/imgui/blob/master/profiler.h

Didn't touch it for a while. There are some improvements to do. Specially floating point imprecisions are accumulating if you profile for a long period.

**Comment by skl131313** [comment]
Ah sweet thanks, I didn't realize you already uploaded it. Yah that's fine, I don't need it to run for that long. Thanks for uploading it!

I'll close this issue as it isn't related to this repo.
